apiVersion: v1
kind: Service
metadata:
  name: boathouse-calculator
spec:
  type: NodePort
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
      nodePort: 30080
  selector:
    app: boathouse-calculator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boathouse-calculator
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: boathouse-calculator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: boathouse-calculator
    spec:
      containers:
      - name: boathouse-calculator
        image: registry.cn-hangzhou.aliyuncs.com/chileeb/smartide-calc:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3001
